/**
 * Tier-1 (process pack) and Tier-2 (feature playbook) retrieval chunks for
 * kb_lookup — transcribed BYTE-FOR-BYTE from the vault design doc
 * (Roshera-vault/Research/2026-07-31-policy-knowledge-base.md, the RETRIEVAL
 * CHUNK blocks in §3 and §4). The doc's measured token estimates are the
 * contract: test/kb_lookup.mjs pins ceil(len/4) of every chunk to the doc's
 * numbers and (when the vault is present) byte-compares the text, so any
 * drift between this file and the doc is a test failure, not a silent skew.
 *
 * GENERATED from the doc's fenced blocks (2026-07-31) — edit the doc first,
 * then re-extract; do not hand-edit chunk text here.
 */

export const PACK_CHUNKS: Record<string, string> = {
  fdm: "FDM. Kernel-certified via dfm_check(pack:\"fdm\"): fdm.overhang (<=45deg from vertical\nunsupported), fdm.min_wall (>=2x nozzle diameter -- 0.8mm at 0.4mm nozzle), fdm.min_bore\n(>=2x nozzle diameter), fdm.trapped_volume (zero enclosed voids). Run all four before any\ndone-claim; report the DfmReport verbatim. Guidance beyond the kernel floor [P, vendor\nrule-of-thumb, not a standard]: 3-perimeter (~1.2mm) structural-wall target for load-bearing\nwalls exceeds the kernel's printability floor -- treat the kernel's 2x as the refusal floor,\n3-perimeter as a design target (open question, architecture doc Q2). Holes print undersized\nin XY (elephant's foot) -- compensate +0.1-0.3mm or plan a reaming pass; pull the nominal\nbore size from kb_lookup(kind:reference, key:clearance_hole or tap_drill), never hand-typed.\nTypical achievable tolerance +/-0.2mm or +/-0.5% of dimension; surface is anisotropic,\nweakest layer adhesion along Z -- orient the load axis in-plane where possible. Cost\ndrivers: build height, support volume, orientation.",
  injection_molding: "Injection molding. Kernel-certified via dfm_check(pack:\"injection_molding\"): mold.draft\nonly (default min 1deg, configurable min_draft_deg). Run before any done-claim. Published\nguidance beyond the kernel default [P, vendor]: 1.5-2deg typical draft, >=0.5deg absolute\nfloor, ~1deg/inch of depth, +1.5deg per 0.025mm of texture depth if textured. mold.undercut\nand mold.trapped_core are NOT implemented (out of scope per molding.rs module docs) --\nundercuts and trapped cores must be checked by eye (section_view) and stated as uncertified,\nnever claimed as checked. Uniform wall thickness and radii at thickness transitions are\nload-bearing DFM practice with no kernel rule -- state as design guidance, not verdict.\nBosses need the same draft as walls; boss OD ~2.5x hole diameter avoids sink. Cost drivers:\ntool complexity (side-actions), cavity count, cycle time (thicker walls cool slower).",
  sla: "SLA -- NOT kernel-certified (no RulePackId::Sla; dfm_check has no \"sla\" enum value). Every\nnumber here is vendor rule-of-thumb [P], stated but never claimed as checked. Min wall:\nsupported >=0.5mm, unsupported >=1.0mm with a filleted base (peel-stress); >=0.8mm\nnon-load-bearing / >=1.5mm functional. Orient near 45deg to the build head; unsupported\nfaces beyond ~45deg from horizontal need support (same geometric logic as FDM overhang,\nunverified here -- do not call dfm_check for it). Tolerance: +/-0.05mm under 50mm,\n+/-0.13-0.2mm over 200mm (cumulative resin shrink 0.2-0.5% on cure). Verify wall thickness\nand overhangs by measure_faces/section_view manually -- dfm_check cannot run this pack.",
  sls: "SLS -- NOT kernel-certified (no RulePackId::Sls). Vendor rule-of-thumb only [P]. Min wall\n>=0.7mm (1mm recommended), >=2.5-3mm under load; glass-filled PA12 needs more (fiber\nbrittleness). No draft needed -- powder-bed is self-supporting, the one process here with no\noverhang/draft constraint at all. Enclosed cavities MUST carry powder-escape holes: >=2\nholes, diameter 2-4mm each (sources diverge on the minimum -- state the range, do not\nsilently pick one). Tolerance ~+/-0.2mm; natural finish is grainy (~Ra 7-12um), vapor\nsmoothing adds 0.05-0.2mm -- fold into clearance calcs via kb_lookup(kind:reference,\nkey:clearance_hole) rather than a hand-adjusted number. Verify wall thickness and\nescape-hole geometry manually; dfm_check cannot run this pack.",
  cnc_3_axis: "CNC 3-axis -- schema-registered (RulePackId::Cnc3Axis) but NO rules implemented; dfm_check's\npack enum is {fdm, injection_molding} only -- this process cannot be run through dfm_check\ntoday. Guidance is vendor rule-of-thumb [P]: internal corner radius >=130% of tool radius;\ndeep-pocket radius >= depth/3 with standard tooling; hole depth <=10:1 diameter, ideal <=4:1.\nTypical tolerance +/-0.1mm (ISO 2768 f/m band -- the standard is real, the +/-0.1mm figure\nattached to it is vendor practice, not a clause citation), Ra 1.6-3.2um as-machined. Minimize\nre-fixturing: every setup change is a tolerance stack-up risk with no kernel check for it --\ntrack feature access/setup count in the Blackboard by hand. Cost drivers: setup count,\nremoval volume, tolerance/finish class.",
  cnc_5_axis: "CNC 5-axis -- no kernel presence at all, not even a schema-only RulePackId. All guidance\nvendor rule-of-thumb [P], never claimed as checked. Value over 3-axis: single-setup access\nto compound-angle/undercut features, eliminating stacked-setup positional error. Aerospace-\ngrade tolerance +/-0.005-0.01mm vs +/-0.02mm+ typical 3-axis; surface finish to Ra 0.4um\n(Al) / 0.8um (Ti) without secondary finishing. Same wall/radius subtractive-material\nguidance as CNC 3-axis applies (no separate 5-axis-specific minimum found this session).\nCost trade-off: higher shop rate per hour, but can net LOWER total cost by removing\nre-fixture setups on geometrically complex parts -- state this trade-off explicitly rather\nthan defaulting to \"more axes is better.\"",
  sheet_metal: "Sheet metal -- schema-registered (RulePackId::SheetMetal), NO rules implemented; dfm_check\ncannot run this pack (developable-surface detection + bend tables are roadmap-only per\nmolding.rs/fdm.rs module docs). Guidance vendor/published rule-of-thumb [P]: inside bend\nradius >=1t generally, 0.5t (soft alloys) to 1.5t (hard alloys) -- never use a blanket\nconstant, resolve per material via kb_lookup(kind:reference, key:bend_allowance) not from\nmemory. K-factor 0.33-0.5 by process/material, same caution. Holes >=4t from any bend line;\nbend reliefs required at flange junctions to prevent tearing. Bend-angle tolerance ~+/-1deg,\nflat-dimension tolerance ~+/-0.2-0.5mm (gauge-dependent, vendor figure, not independently\nre-verified). Cost drivers: bend count (per-bend setup), nesting efficiency, hardware\ninsertion.",
  casting: "Casting (die-casting reference) -- no kernel presence at all. Vendor rule-of-thumb only [P];\nsources diverge on the fillet minimum -- surface the conflict, do not silently pick. Draft\n~1deg per 25mm of cavity depth, typical range 1-3deg -- essentially the same ratio as\nmolding's ~1deg/inch; cross-check if the part might move processes. Minimum wall ~1mm,\nuniform section critical (thicker sections raise cycle time materially -- one source:\n+15-25% cycle time going 2.5->5mm in aluminum). Internal fillet >=1.5x wall thickness;\nminimum fillet 0.5-1.5mm (source-dependent, do not blanket-pick). Tolerance is alloy/process\nspecific -- do not state a default; this is a task-specific sourcing question, not a house\nnumber. Cost driver: tooling amortization -- casting is a volume play.",
};

export const PLAYBOOK_CHUNKS: Record<string, string> = {
  hole: "Hole (through/blind/counterbore/countersink/tapped). Sketch one circle (nested for\ncounterbore/countersink) on the target face; center Coincident to a reference construction\npoint (Distance off two reference edges, or Concentric for patterns), circle Radius/\nDiameter. psketch_certify must read FullyConstrained, dof:0 before extrude/cut. Cut LAST\nrelative to primary structure, referencing a stable parent face (fillet/chamfer don't mint\nPID lineage yet -- known kernel gap, not an agent error). Through: unbounded cut or\ndrill_pattern (refuses overlapping holes, chord spacing > 2*hole_r). Blind: cut to a\nmeasured depth, verify as-built with section_view, never the intended depth. Counterbore/\ncountersink: two coaxial circles, Concentric + independent Radius each. Tapped: bore at\ntap-drill diameter from kb_lookup(kind:reference, key:tap_drill) -- kernel has no thread-form\nprimitive, state that in the Blackboard. Verify: dfm_check bore-floor if the process has one\n(fdm.min_bore today); gdt_fcf position on a locating pattern; verify_part.",
  boss: "Boss. Sketch a circle on the parent face, center Coincident with the mating hole's axis if\nfastened -- share the hole's own reference, not a second dimension chain. DOF0: center\nCoincident/Distance, Diameter/Radius dimensioned. Extrude the boss from stable parent\nstructure before any dress-up fillet on that face; if it carries a hole, extrude first then\ncut the bore against the boss's OWN new face. Molded/cast bosses need draft (mold.draft,\nkernel-certified) and a base fillet against sink (uncertified guidance). Boss OD relative to\nhole from kb_lookup(kind:reference), not hand-picked. Verify: dfm_check(injection_molding)\ndraft on boss faces if molded; mass_properties/section_view for as-built height/OD;\nverify_part.",
  rib: "Rib. Sketch a thin profile on a plane_from_face between the wall it stiffens and its far\nextent; Distance constrains thickness -- a rib IS the thin-wall case fdm.min_wall/general-\nthickness checks apply to. DOF0: parallel to parent wall, Distance for thickness, Distance/\nCoincident for height and position (3-4 constraints total). Extrude after the primary wall\nexists (stable parent); before fillet dress-up at the rib-to-wall junction. Molded rib\nthickness ~50-60% of the adjoining wall avoids opposite-face sink [P, uncertified -- no\nkernel check]. Verify: dfm_check(fdm) min_wall on the rib itself for FDM (free ride, a rib is\na wall); measure_faces for as-built thickness vs intended.",
  gusset: "Gusset. Sketch a triangular/trapezoidal profile bridging two faces on the plane containing\nboth directions. DOF0: both attachment edges Coincident/Tangent to their parent faces, plus\nthickness Distance and the two leg lengths/angle -- a fully dimensioned triangle reaches\nDOF0 once attachment points are fixed. Extrude after both bridged faces exist and are\nstable; before fillet dress-up at either junction. Same thickness DFM check as a rib. A root\nfillet (stress concentration) is a design decision with NO kernel verdict -- state as\nguidance, never as a passed check.",
  bearing_seat: "Bearing seat. Sketch a circle sized to the bearing OD (housing bore) or ID (shaft seat) from\nkb_lookup(kind:reference, key:fit_class) -- never hand-typed. DOF0: Concentric to the shaft/\nbore axis, diameter from the fit-class lookup. label_create the rotational axis first so\nlater features reference \"the bearing bore axis\" by name, not a transient face index.\nCanonical C12 case: gdt_datum the bore axis (qualifies as an axis datum on a cylindrical\nface), gdt_fcf position on it relative to the primary seating face, gdt_fcf perpendicularity\non the seating shoulder against the bore axis if it must seat square -- BOTH kernel-certified\ntoday. Verify: both FCF verdicts; mass_properties/measure_faces for bore diameter vs fit-\nclass target; verify_part.",
  flange: "Flange. Sketch the outer profile (disc/plate edge) plus the bolt-hole pattern via\ndrill_pattern (compound one-call feature, no separate sketch DOF for the ring). DOF0: outer\nprofile fully dimensioned (diameter, or width/height + fillet radii). Order: plate/disc\nfirst, THEN drill_pattern for bolt holes (subtracts from the existing solid), THEN fillet/\nchamfer dress-up last. GD&T -- textbook case: datum A = mating/seating face (primary, 3\nDOF), datum B = one bolt-hole axis or locating feature (secondary), position FCF on the FULL\nbolt pattern relative to A|B; state the datum logic in prose before the FCF. Verify: gdt_fcf\nposition; dfm_check for the process's applicable rule; verify_part.",
  bolt_pattern: "Bolt pattern (standalone, not on a flange). drill_pattern in one call: center (REQUIRED\noff-origin), count, ring_r, hole_r from kb_lookup(kind:reference, key:clearance_hole) --\nnever hand-typed; depth overshoots both faces. The tool itself refuses overlapping holes\n(chord spacing > 2*hole_r) -- kernel-enforced. Not sketch-based: drill_pattern's own\nparameters are the full definition; label_create the defining axis/plane if later features\nreference it. Clearance class (close/medium/free) is a Tier-3 parameter, NOT a house\ndefault -- open question (architecture doc Q6). Verify: dfm_check bore-floor if applicable;\ngdt_fcf position against the established DRF; verify_part (drill_pattern halts on first\nunsound step, but this is still the done-claim gate).",
  snap_fit: "Snap-fit -- NO kernel/analyzer backing at all; flag this explicitly every time. Sketch a\ncantilever-beam profile (arm length, base thickness, taper, hook engagement depth/angle) off\nthe parent wall. DOF0: arm profile fully dimensioned. Extrude after the parent wall exists;\nthe hook is an undercut, usually a boolean subtract or swept cut. FDM: the undercut prints\nas an overhang and DOES inherit fdm.overhang exposure -- check it. Molding: the hook IS an\nundercut needing mold.undercut, which is NOT implemented -- flag the gap, this stays\nprose-only guidance for molded snap-fits. Verify: mass_properties/measure_faces for arm\nthickness (deflection depends on it -- hand-calc only, mark not-kernel-certified per\narchitecture doc Q8); dfm_check(fdm) if FDM. State explicitly: retention force is NOT\nkernel-verifiable today.",
  // dimensioning -- added 2026-08-01, NOT vault-doc-sourced (the other 8 chunks above
  // are byte-extracted from Roshera-vault/Research/2026-07-31-policy-knowledge-base.md;
  // this one is authored directly here per the same-day dimensioning-KB task. Do not
  // fold it into a future vault re-extraction pass without carrying this text into the
  // doc first.
  dimensioning: "Dimensioning (ASME Y14.5 / ISO 129 drafting practice -- judgement, not a kernel rule).\nDimension from DATUMS, not feature-to-feature chains: a chain accumulates every link's\ntolerance into the last link (stack-up grows with chain length); a baseline (every\ndimension off one shared reference) does not -- each dimension carries only its own\ntolerance. Dimension by FUNCTION: what must fit, mate, or seal decides which faces get\ntoleranced tightly, not the order features were built in psketch/extrude. SIZE and\nLOCATION are separate dimensions -- a hole gets a diameter (size, on the hole's own\nsketch) and a position (location, off a datum) as two independent callouts; merging\nthem is a drafting error, not a shortcut. ONE DIMENSION PER DEGREE OF FREEDOM:\npsketch_certify's DOF0 gate is the enforcement -- dof>0 means under-dimensioned, a\nredundant/conflicting-constraint refusal means the same freedom was dimensioned\ntwice; fix the scheme, do not retry the same constraint. NEVER dimension to a\nconstruction line or a tangent point -- both move when an adjacent radius or\nparameter changes, so the callout silently drifts; reference a real edge, face, or\ncenter psketch can hold. Scheme choice and its stack-up consequence: BASELINE --\nevery dimension off one datum, no stack-up, more callouts -- for functionally\nrelated features needing independent accuracy. CHAIN -- each dimension off the\nprevious feature, error compounds linearly with link count -- only where\nadjacent-feature spacing is what matters (e.g. a repeat pitch). ORDINATE -- all\ndimensions read as coordinates from one zero point, same no-stack-up property as\nbaseline, more compact -- for dense hole patterns. Certified scope: gdt_datum +\ngdt_fcf give an exact kernel verdict for flatness, perpendicularity, parallelism,\nand position -- RFS (regardless of feature size) ONLY, no MMC/LMC modifier today.\nEvery other dimension -- nominal sizes, ISO 2768 general tolerances, the\nbaseline-vs-chain choice itself -- is design intent captured in the model: real,\nbut state it as intent, never as a passed check.",
};
