//! OBJ file format support

use shared_types::{
    geometry::MaterialProperties, // Use the geometry MaterialProperties specifically
    ExportError,
    Mesh,
};

/// Generate OBJ content
pub fn generate_obj(mesh: &Mesh, name: &str) -> Result<String, ExportError> {
    let mut content = format!("# OBJ file: {}\n", name);
    content.push_str("# Generated by Roshera CAD\n\n");

    // Write object name
    content.push_str(&format!("o {}\n\n", name));

    // Write vertices
    for i in (0..mesh.vertices.len()).step_by(3) {
        content.push_str(&format!(
            "v {} {} {}\n",
            mesh.vertices[i],
            mesh.vertices[i + 1],
            mesh.vertices[i + 2]
        ));
    }

    content.push_str("\n");

    // Write normals if available
    if !mesh.normals.is_empty() {
        for i in (0..mesh.normals.len()).step_by(3) {
            content.push_str(&format!(
                "vn {} {} {}\n",
                mesh.normals[i],
                mesh.normals[i + 1],
                mesh.normals[i + 2]
            ));
        }
        content.push_str("\n");
    }

    // Write faces
    for i in (0..mesh.indices.len()).step_by(3) {
        let i0 = mesh.indices[i] + 1; // OBJ uses 1-based indexing
        let i1 = mesh.indices[i + 1] + 1;
        let i2 = mesh.indices[i + 2] + 1;

        if mesh.normals.is_empty() {
            content.push_str(&format!("f {} {} {}\n", i0, i1, i2));
        } else {
            content.push_str(&format!("f {}//{} {}//{} {}//{}\n", i0, i0, i1, i1, i2, i2));
        }
    }

    Ok(content)
}

#[cfg(test)]
pub fn export_obj_with_material(
    mesh: &Mesh,
    material: &MaterialProperties,
    name: &str,
) -> (String, String) {
    let mut obj_content = format!("# OBJ file: {}\n", name);
    obj_content.push_str(&format!("mtllib {}.mtl\n\n", name));

    // Write vertices
    for i in (0..mesh.vertices.len()).step_by(3) {
        obj_content.push_str(&format!(
            "v {} {} {}\n",
            mesh.vertices[i],
            mesh.vertices[i + 1],
            mesh.vertices[i + 2]
        ));
    }

    // Write normals
    if !mesh.normals.is_empty() {
        obj_content.push_str("\n");
        for i in (0..mesh.normals.len()).step_by(3) {
            obj_content.push_str(&format!(
                "vn {} {} {}\n",
                mesh.normals[i],
                mesh.normals[i + 1],
                mesh.normals[i + 2]
            ));
        }
    }

    // Write material and faces
    obj_content.push_str("\n");
    obj_content.push_str("o mesh_0\n");
    obj_content.push_str("usemtl material_0\n");

    for i in (0..mesh.indices.len()).step_by(3) {
        let i0 = mesh.indices[i] + 1;
        let i1 = mesh.indices[i + 1] + 1;
        let i2 = mesh.indices[i + 2] + 1;

        if mesh.normals.is_empty() {
            obj_content.push_str(&format!("f {} {} {}\n", i0, i1, i2));
        } else {
            obj_content.push_str(&format!("f {}//{} {}//{} {}//{}\n", i0, i0, i1, i1, i2, i2));
        }
    }

    // Create MTL content
    let mut mtl_content = format!("# MTL file: {}\n\n", name);
    mtl_content.push_str("newmtl material_0\n");
    mtl_content.push_str(&format!(
        "Kd {} {} {}\n",
        material.diffuse_color[0], material.diffuse_color[1], material.diffuse_color[2]
    ));
    mtl_content.push_str(&format!(
        "Ks {} {} {}\n",
        material.metallic, material.metallic, material.metallic
    ));
    mtl_content.push_str(&format!("Ns {}\n", (1.0 - material.roughness) * 1000.0));

    (obj_content, mtl_content)
}
