//! Thin wrapper over [`ruststep::parser::parse`].
//!
//! ruststep gives us a robust, schema-agnostic AST for an ISO 10303-21
//! exchange structure: header records, data sections, and entity
//! instances with their generic [`ruststep::ast::Parameter`] tree.
//! That is precisely the layer we want — we do **not** depend on
//! ruststep's typed AP203 entity bindings (generated by `espr`),
//! because our semantic mapping into a [`BRepModel`] is owned by the
//! handlers in [`super::handlers`].
//!
//! Pre-processing: this module strips `/* ... */` block comments from
//! the input before handing it to the underlying parser. Open CASCADE
//! emits a non-conforming `META-MATIC-ID` comment near the top of
//! every exported file; while most STEP toolchains tolerate this,
//! ruststep's grammar is strict to ISO 10303-21 and rejects it. The
//! comment carries no geometric meaning, so stripping is the
//! pragmatic move.
//!
//! Line-comment style (`-- ...` to end of line, allowed by the EXPRESS
//! schema language but rare in STEP data files) is **not** handled —
//! ISO 10303-21 doesn't sanction it for the exchange structure, and
//! we haven't seen a file in the wild that uses it. If we ever do,
//! this is the single place to extend.

use ruststep::ast::Exchange;

use crate::ExportError;

/// Pre-process raw STEP file bytes into a string ruststep can parse.
///
/// Currently strips C-style block comments `/* ... */`. Returns the
/// cleaned string and the number of bytes removed (useful for
/// diagnostics).
pub fn preprocess(input: &str) -> (String, usize) {
    let mut out = String::with_capacity(input.len());
    let bytes = input.as_bytes();
    let mut i = 0;
    let mut stripped = 0usize;
    while i < bytes.len() {
        if i + 1 < bytes.len() && bytes[i] == b'/' && bytes[i + 1] == b'*' {
            // Block-comment open. Scan to the next `*/`. If unterminated,
            // treat the rest of the file as comment (defensive — every
            // real STEP file is properly terminated).
            let start = i;
            i += 2;
            while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                i += 1;
            }
            if i + 1 < bytes.len() {
                i += 2; // skip closing */
            } else {
                i = bytes.len();
            }
            stripped += i - start;
            // Replace the comment with a single space so token boundaries
            // are preserved (`#10=A/*x*/(1);` must not become `#10=A(1);`
            // — though that one happens to still parse, a comment between
            // two adjacent tokens shouldn't fuse them).
            out.push(' ');
        } else {
            // Push the byte verbatim. STEP files are 7-bit ASCII per
            // ISO 10303-21 §6.4, so direct byte-to-char is safe.
            out.push(bytes[i] as char);
            i += 1;
        }
    }
    (out, stripped)
}

/// Parse a STEP exchange structure into ruststep's schema-agnostic AST.
///
/// `path_hint` is used only for the error message when parsing fails;
/// it does not affect the parse itself.
pub fn parse_step(input: &str, path_hint: &str) -> Result<Exchange, ExportError> {
    let (cleaned, _stripped) = preprocess(input);
    ruststep::parser::parse(&cleaned).map_err(|e| ExportError::ExportFailed {
        reason: format!("STEP parse failed for {path_hint}: {e}"),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preprocess_strips_block_comment() {
        let input = "ISO-10303-21;\n/* META-MATIC-ID: abc */\nHEADER;";
        let (out, stripped) = preprocess(input);
        assert!(!out.contains("META-MATIC-ID"));
        assert!(out.contains("ISO-10303-21"));
        assert!(out.contains("HEADER"));
        assert!(stripped > 0);
    }

    #[test]
    fn preprocess_preserves_token_boundary_between_comments() {
        // A comment between two tokens must not fuse them.
        let input = "FOO/* x */BAR";
        let (out, _) = preprocess(input);
        assert_eq!(out, "FOO BAR");
    }

    #[test]
    fn preprocess_unterminated_comment_eats_rest_of_file() {
        // Defensive — non-conforming, but should not panic.
        let input = "BEFORE/* unterminated";
        let (out, _) = preprocess(input);
        assert_eq!(out, "BEFORE ");
    }

    #[test]
    fn preprocess_no_comments_is_identity() {
        let input = "ISO-10303-21;\nHEADER;\nENDSEC;";
        let (out, stripped) = preprocess(input);
        assert_eq!(out, input);
        assert_eq!(stripped, 0);
    }

    #[test]
    fn parse_minimal_exchange_structure() {
        // Bare-minimum valid STEP exchange.
        let input = "ISO-10303-21;\n\
                     HEADER;\n\
                     FILE_DESCRIPTION(('test'),'2;1');\n\
                     FILE_NAME('t.step','2026-01-01T00:00:00',(''),(''),'','','');\n\
                     FILE_SCHEMA(('AUTOMOTIVE_DESIGN'));\n\
                     ENDSEC;\n\
                     DATA;\n\
                     #1=CARTESIAN_POINT('',(0.,0.,0.));\n\
                     ENDSEC;\n\
                     END-ISO-10303-21;\n";
        let parsed = parse_step(input, "test").expect("minimal exchange should parse");
        assert!(!parsed.data.is_empty(), "expected at least one DATA section");
        let entities = &parsed.data[0].entities;
        assert_eq!(entities.len(), 1, "expected one entity");
    }

    #[test]
    fn parse_with_occt_style_comment() {
        // The shape that broke the hand-rolled parser.
        let input = "ISO-10303-21;\n\
                     /* META-MATIC-ID: a38da557 */\n\
                     HEADER;\n\
                     FILE_DESCRIPTION(('test'),'2;1');\n\
                     FILE_NAME('t.step','2026-01-01T00:00:00',(''),(''),'','','');\n\
                     FILE_SCHEMA(('AUTOMOTIVE_DESIGN'));\n\
                     ENDSEC;\n\
                     DATA;\n\
                     #1=CARTESIAN_POINT('',(0.,0.,0.));\n\
                     ENDSEC;\n\
                     END-ISO-10303-21;\n";
        let parsed = parse_step(input, "test").expect("comment must not break parse");
        assert_eq!(parsed.data[0].entities.len(), 1);
    }
}
