//! Convex polyhedral cones in R³ — the substrate for smooth-B-Rep contact
//! determination (Crozet, Ch. 3).
//!
//! A pointed convex polyhedral cone `C ⊆ R³` at the origin has two dual
//! representations:
//!   * **V-rep** `generators`: extreme unit rays, `C = { Σ λᵢ gᵢ : λᵢ ≥ 0 }`.
//!   * **H-rep** `supports`: outward unit face normals, `C = { x : x·sⱼ ≤ 0 }`.
//!
//! The two are **polar duals**: the polar cone `C° = { y : x·y ≤ 0 ∀ x ∈ C }`
//! has `C`'s supports as its generators and vice-versa, so [`polar`] is just a
//! swap. The V↔H conversion is one routine ([`dual_extreme_rays`]): the extreme
//! rays of `{ y : vᵢ·y ≤ 0 }` are the pairwise plane intersections `vᵢ × vⱼ`
//! kept iff every other constraint holds — which converts generators→supports
//! *and* supports→generators (they're duals of each other).
//!
//! These power the CD critical-point gate (a footpoint pair is a true local
//! minimum-distance only if the separation direction lies in both features'
//! normal cones) and feature-pair culling (two cones with no common ray cannot
//! contact).
//!
//! # Scope (slice 1)
//! Correct for pointed cones whose generators span ≥ 3 dimensions (the vertex-
//! cone case) and for the full-space cone. Planar (2-generator edge) cones and
//! the cone-intersection / dilation operations are the next slices.
//!
//! # References
//! Crozet, *Efficient contact determination between B-Rep solids*, §3.2–3.4;
//! Rockafellar, *Convex Analysis*, §14 (polar cones).
#![allow(clippy::indexing_slicing)]

use crate::math::Vector3;

/// Angular epsilon for cone membership / dedup (radians-ish, on unit vectors).
const CONE_EPS: f64 = 1e-9;

/// A convex polyhedral cone in R³, stored in both dual representations.
#[derive(Debug, Clone)]
pub struct PolyhedralCone {
    /// Extreme unit rays (V-rep). Empty ⇒ the cone is `{0}` or the full space
    /// (disambiguated by `supports`).
    generators: Vec<Vector3>,
    /// Outward unit face normals (H-rep): `x ∈ C ⇔ x·sⱼ ≤ 0 ∀ j`. Empty with
    /// non-empty `generators` ⇒ the full space R³ (no constraints).
    supports: Vec<Vector3>,
}

impl PolyhedralCone {
    /// The whole space R³ (no supporting constraints). `contains` is always
    /// true. A sentinel generator records non-emptiness.
    pub fn full_space() -> Self {
        Self {
            generators: vec![
                Vector3::X,
                -Vector3::X,
                Vector3::Y,
                -Vector3::Y,
                Vector3::Z,
                -Vector3::Z,
            ],
            supports: Vec::new(),
        }
    }

    /// Build a cone from its generating rays (V-rep). Computes the dual
    /// supports (H-rep) and **canonicalizes the V-rep to its extreme rays** —
    /// redundant input rays (those interior to the conic hull of the others)
    /// are dropped, so `generators` is minimal and `generators ⇄ supports` is a
    /// clean polar round-trip. Rays are normalized and de-duplicated; zero rays
    /// are dropped.
    pub fn from_generators(rays: &[Vector3]) -> Self {
        let raw = normalize_dedup(rays);
        let supports = dual_extreme_rays(&raw);
        // The extreme rays are determined by the faces; recovering them from
        // the supports yields the minimal generator set. (When `supports` is
        // empty the cone is the full space / degenerate — keep the raw rays.)
        let generators = if supports.is_empty() {
            raw
        } else {
            dual_extreme_rays(&supports)
        };
        Self {
            generators,
            supports,
        }
    }

    /// The **normal cone** of a vertex: the cone generated by the outward
    /// normals of the faces meeting there. Its [`polar`] is the tangent cone
    /// (the directions that stay inside the solid to first order).
    pub fn normal_cone(face_outward_normals: &[Vector3]) -> Self {
        Self::from_generators(face_outward_normals)
    }

    /// Extreme unit rays (V-rep).
    pub fn generators(&self) -> &[Vector3] {
        &self.generators
    }

    /// Outward unit face normals (H-rep).
    pub fn supports(&self) -> &[Vector3] {
        &self.supports
    }

    /// True iff the cone is all of R³ (no supporting constraints).
    pub fn is_full_space(&self) -> bool {
        self.supports.is_empty() && !self.generators.is_empty()
    }

    /// Polar (dual) cone `C° = { y : x·y ≤ 0 ∀ x ∈ C }`. By the polar-duality
    /// theorem this swaps the two representations.
    pub fn polar(&self) -> Self {
        Self {
            generators: self.supports.clone(),
            supports: self.generators.clone(),
        }
    }

    /// Does direction `d` (need not be unit; the zero vector is the apex, in
    /// every cone) lie inside the cone? Tested against the H-rep.
    pub fn contains(&self, d: &Vector3) -> bool {
        if self.is_full_space() {
            return true;
        }
        // A cone with no generators is the trivial cone {0}: only the apex
        // lies in it. (Without this guard the `all()` over empty supports below
        // would vacuously accept every direction.)
        if self.generators.is_empty() {
            return d.magnitude() < CONE_EPS;
        }
        let scale = d.magnitude().max(1.0);
        self.supports.iter().all(|s| d.dot(s) <= CONE_EPS * scale)
    }

    /// True iff the cone is the trivial `{0}` (apex only).
    pub fn is_zero(&self) -> bool {
        self.generators.is_empty() && self.supports.is_empty()
    }
}

/// Extreme rays of the dual cone `{ y : vᵢ·y ≤ 0 ∀ i }`.
///
/// Each extreme ray lies on the intersection of two bounding planes, so it is
/// `± (vᵢ × vⱼ)` for some pair, kept iff it satisfies every remaining
/// constraint. Because generators and supports are polar duals, this single
/// routine performs both V→H and H→V conversion. O(n³) — fine for the small
/// face-counts of vertex cones.
fn dual_extreme_rays(vecs: &[Vector3]) -> Vec<Vector3> {
    let n = vecs.len();
    let mut rays: Vec<Vector3> = Vec::new();
    for i in 0..n {
        for j in (i + 1)..n {
            let cross = vecs[i].cross(&vecs[j]);
            let unit = match cross.normalize() {
                Ok(v) => v,
                Err(_) => continue, // parallel generators — no shared edge
            };
            for &sign in &[1.0_f64, -1.0] {
                let r = unit * sign;
                if vecs.iter().all(|v| v.dot(&r) <= CONE_EPS) {
                    if !rays.iter().any(|e| (*e - r).magnitude() < CONE_EPS) {
                        rays.push(r);
                    }
                }
            }
        }
    }
    rays
}

/// Normalize each ray and drop near-duplicates and zeros.
fn normalize_dedup(rays: &[Vector3]) -> Vec<Vector3> {
    let mut out: Vec<Vector3> = Vec::new();
    for r in rays {
        if let Ok(u) = r.normalize() {
            if !out.iter().any(|e| (*e - u).magnitude() < CONE_EPS) {
                out.push(u);
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    // ---- known closed-form: cube vertex ---------------------------------

    #[test]
    fn cube_vertex_normal_cone_supports() {
        // Vertex of [0,L]³ at the +++ corner: incident faces' outward normals
        // are +X,+Y,+Z; the normal cone is the +++ octant, supports the −−−.
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        assert_eq!(c.supports().len(), 3);
        for expected in [-Vector3::X, -Vector3::Y, -Vector3::Z] {
            assert!(
                c.supports()
                    .iter()
                    .any(|s| (*s - expected).magnitude() < 1e-9),
                "missing support {expected:?} in {:?}",
                c.supports()
            );
        }
    }

    #[test]
    fn cube_vertex_membership() {
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        assert!(c.contains(&Vector3::new(1.0, 1.0, 1.0)), "interior");
        assert!(c.contains(&Vector3::X), "boundary ray");
        assert!(!c.contains(&Vector3::new(-1.0, -1.0, -1.0)), "antipode");
        assert!(!c.contains(&(-Vector3::X)), "opposite face");
    }

    #[test]
    fn cube_vertex_tangent_cone_is_opposite_octant() {
        // Polar of the +++ normal cone is the −−− tangent cone (inward dirs).
        let tangent = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]).polar();
        assert!(tangent.contains(&Vector3::new(-1.0, -1.0, -1.0)), "inward");
        assert!(!tangent.contains(&Vector3::new(1.0, 1.0, 1.0)), "outward");
    }

    // ---- property tests over random pointed cones -----------------------

    /// A pointed cone: 3–5 generators all within the hemisphere around +Z
    /// (z-component ≥ 0.3), so the cone is strictly contained in z > 0 and its
    /// antipodes are guaranteed outside.
    fn pointed_cone() -> impl Strategy<Value = (PolyhedralCone, Vec<Vector3>)> {
        prop::collection::vec((-1.0f64..1.0, -1.0f64..1.0, 0.3f64..1.0), 3..6).prop_filter_map(
            "non-degenerate pointed cone",
            |raw| {
                let gens: Vec<Vector3> = raw
                    .into_iter()
                    .filter_map(|(x, y, z)| Vector3::new(x, y, z).normalize().ok())
                    .collect();
                if gens.len() < 3 {
                    return None;
                }
                let cone = PolyhedralCone::from_generators(&gens);
                // Need a genuinely bounded (pointed, supported) cone for the
                // antipode oracle to hold.
                if cone.supports().is_empty() {
                    return None;
                }
                Some((cone, gens))
            },
        )
    }

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(256))]

        /// Every generator lies in its own cone.
        #[test]
        fn generators_are_contained((cone, gens) in pointed_cone()) {
            for g in &gens {
                prop_assert!(cone.contains(g), "generator {g:?} not in cone {cone:?}");
            }
        }

        /// Any non-negative combination of generators is inside; its antipode
        /// (for a pointed cone) is outside. Labels membership without solving it.
        #[test]
        fn conic_combos_in_antipodes_out(
            (cone, gens) in pointed_cone(),
            weights in prop::collection::vec(0.0f64..1.0, 3..6),
        ) {
            let mut d = Vector3::ZERO;
            for (g, &w) in gens.iter().zip(weights.iter()) {
                d = d + *g * w;
            }
            if d.magnitude() < 1e-6 {
                return Ok(()); // all-zero weights → apex, skip
            }
            prop_assert!(cone.contains(&d), "conic combo {d:?} not in cone");
            prop_assert!(!cone.contains(&(-d)), "antipode {:?} in pointed cone", -d);
        }

        /// Polar duality round-trips: recomputing the extreme rays of the dual
        /// of the supports recovers the generators (as a set). This validates
        /// the V↔H conversion against itself.
        #[test]
        fn duality_round_trips((cone, _gens) in pointed_cone()) {
            let recovered = super::dual_extreme_rays(cone.supports());
            // recovered should equal cone.generators() as a set.
            for g in cone.generators() {
                prop_assert!(
                    recovered.iter().any(|r| (*r - *g).magnitude() < 1e-7),
                    "generator {g:?} not recovered from supports; got {recovered:?}"
                );
            }
            prop_assert_eq!(recovered.len(), cone.generators().len());
        }

        /// `polar` is an involution: `(C°)° == C`.
        #[test]
        fn polar_is_involution((cone, _gens) in pointed_cone()) {
            let back = cone.polar().polar();
            prop_assert_eq!(back.generators().len(), cone.generators().len());
            for g in cone.generators() {
                prop_assert!(back.generators().iter().any(|h| (*h - *g).magnitude() < 1e-9));
            }
        }
    }

    // ---- helpers --------------------------------------------------------

    fn nrm(x: f64, y: f64, z: f64) -> Vector3 {
        Vector3::new(x, y, z).normalize().expect("nonzero")
    }
    fn has_vec(set: &[Vector3], v: Vector3) -> bool {
        set.iter().any(|s| (*s - v).magnitude() < 1e-9)
    }

    // ---- more known closed-form cases -----------------------------------

    #[test]
    fn cube_vertex_neg_corner_supports() {
        let c = PolyhedralCone::normal_cone(&[-Vector3::X, -Vector3::Y, -Vector3::Z]);
        assert_eq!(c.supports().len(), 3);
        for s in [Vector3::X, Vector3::Y, Vector3::Z] {
            assert!(has_vec(c.supports(), s), "missing {s:?}");
        }
    }

    #[test]
    fn square_pyramid_apex_has_four_supports() {
        let g = [
            nrm(1.0, 1.0, 1.0),
            nrm(1.0, -1.0, 1.0),
            nrm(-1.0, -1.0, 1.0),
            nrm(-1.0, 1.0, 1.0),
        ];
        let c = PolyhedralCone::from_generators(&g);
        assert_eq!(c.generators().len(), 4, "four extreme rays");
        assert_eq!(c.supports().len(), 4, "four faces");
        assert!(c.contains(&Vector3::Z), "axis is interior");
        assert!(!c.contains(&(-Vector3::Z)), "anti-axis outside");
    }

    #[test]
    fn pentagonal_pyramid_apex_has_five_supports() {
        let g: Vec<Vector3> = (0..5)
            .map(|k| {
                let a = std::f64::consts::TAU * (k as f64) / 5.0;
                nrm(a.cos(), a.sin(), 1.0)
            })
            .collect();
        let c = PolyhedralCone::from_generators(&g);
        assert_eq!(c.generators().len(), 5);
        assert_eq!(c.supports().len(), 5);
        assert!(c.contains(&Vector3::Z));
    }

    #[test]
    fn tetra_apex_three_supports() {
        let g = [
            nrm(1.0, 1.0, 1.0),
            nrm(1.0, -1.0, -1.0),
            nrm(-1.0, 1.0, -1.0),
        ];
        let c = PolyhedralCone::from_generators(&g);
        assert_eq!(c.supports().len(), 3);
    }

    // ---- canonicalization / cleaning ------------------------------------

    #[test]
    fn redundant_interior_generator_dropped() {
        // (1,1,1) is interior to cone(X,Y,Z) — not extreme.
        let c = PolyhedralCone::from_generators(&[
            Vector3::X,
            Vector3::Y,
            Vector3::Z,
            Vector3::new(1.0, 1.0, 1.0),
        ]);
        assert_eq!(c.generators().len(), 3, "redundant ray removed");
        assert_eq!(c.supports().len(), 3);
    }

    #[test]
    fn duplicate_generators_deduped() {
        let c = PolyhedralCone::from_generators(&[Vector3::X, Vector3::Y, Vector3::Z, Vector3::X]);
        assert_eq!(c.generators().len(), 3);
    }

    #[test]
    fn zero_rays_dropped() {
        let c =
            PolyhedralCone::from_generators(&[Vector3::X, Vector3::Y, Vector3::Z, Vector3::ZERO]);
        assert_eq!(c.generators().len(), 3);
    }

    #[test]
    fn non_unit_rays_are_normalized() {
        let c = PolyhedralCone::from_generators(&[
            Vector3::X * 5.0,
            Vector3::Y * 3.0,
            Vector3::Z * 0.1,
        ]);
        for g in c.generators() {
            assert!(
                (g.magnitude() - 1.0).abs() < 1e-9,
                "generator not unit: {g:?}"
            );
        }
        for s in c.supports() {
            assert!(
                (s.magnitude() - 1.0).abs() < 1e-9,
                "support not unit: {s:?}"
            );
        }
    }

    #[test]
    fn permutation_invariant_supports() {
        let a = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        let b = PolyhedralCone::normal_cone(&[Vector3::Z, Vector3::X, Vector3::Y]);
        assert_eq!(a.supports().len(), b.supports().len());
        for s in a.supports() {
            assert!(
                has_vec(b.supports(), *s),
                "support {s:?} not permutation-stable"
            );
        }
    }

    // ---- membership edge cases ------------------------------------------

    #[test]
    fn apex_is_in_every_cone() {
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        assert!(c.contains(&Vector3::ZERO));
    }

    #[test]
    fn membership_is_scale_invariant() {
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        let d = Vector3::new(1.0, 2.0, 3.0);
        assert_eq!(c.contains(&d), c.contains(&(d * 10.0)));
        assert_eq!(c.contains(&d), c.contains(&(d * 0.01)));
    }

    #[test]
    fn just_inside_and_outside_a_face() {
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        assert!(
            c.contains(&Vector3::new(0.01, 1.0, 1.0)),
            "just inside +x face"
        );
        assert!(
            !c.contains(&Vector3::new(-0.01, 1.0, 1.0)),
            "just outside +x face"
        );
    }

    #[test]
    fn midpoint_of_two_generators_is_contained() {
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        assert!(c.contains(&(Vector3::X + Vector3::Y)));
        assert!(c.contains(&(Vector3::X + Vector3::Z)));
    }

    #[test]
    fn negated_support_is_inside_the_octant() {
        // For the octant, supports are −X,−Y,−Z; negating one gives a boundary
        // generator (X / Y / Z), which is contained.
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        for s in c.supports() {
            assert!(
                c.contains(&(-*s)),
                "negated support {:?} should be inside",
                -*s
            );
        }
    }

    // ---- full space / zero cone -----------------------------------------

    #[test]
    fn full_space_contains_everything() {
        let c = PolyhedralCone::full_space();
        assert!(c.is_full_space());
        assert!(c.contains(&Vector3::new(7.0, -3.0, 2.0)));
        assert!(c.contains(&(-Vector3::Z)));
    }

    #[test]
    fn generators_spanning_r3_is_full_space() {
        // Six axis directions positively span R³.
        let c = PolyhedralCone::from_generators(&[
            Vector3::X,
            -Vector3::X,
            Vector3::Y,
            -Vector3::Y,
            Vector3::Z,
            -Vector3::Z,
        ]);
        assert!(c.supports().is_empty(), "spanning cone has no supports");
        assert!(c.contains(&Vector3::new(1.0, -1.0, 1.0)));
    }

    #[test]
    fn empty_cone_contains_only_apex() {
        let c = PolyhedralCone::from_generators(&[]);
        assert!(c.is_zero());
        assert!(c.contains(&Vector3::ZERO));
        assert!(!c.contains(&Vector3::X));
    }

    // ---- polar / tangent relationships ----------------------------------

    #[test]
    fn polar_swaps_generators_and_supports() {
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        let p = c.polar();
        assert_eq!(p.generators().len(), c.supports().len());
        for s in c.supports() {
            assert!(has_vec(p.generators(), *s));
        }
        for g in c.generators() {
            assert!(has_vec(p.supports(), *g));
        }
    }

    #[test]
    fn tangent_cone_contains_inward_axis() {
        let tangent = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]).polar();
        assert!(tangent.contains(&Vector3::new(-1.0, -1.0, -1.0)));
        assert!(!tangent.contains(&Vector3::new(1.0, 1.0, 1.0)));
    }

    #[test]
    fn narrow_cone_excludes_side_directions() {
        // Three rays bunched near +Z.
        let c = PolyhedralCone::from_generators(&[
            nrm(0.1, 0.0, 1.0),
            nrm(-0.05, 0.087, 1.0),
            nrm(-0.05, -0.087, 1.0),
        ]);
        assert!(c.contains(&Vector3::Z), "axis inside narrow cone");
        assert!(!c.contains(&Vector3::X), "side direction outside");
        assert!(!c.contains(&(-Vector3::Z)), "anti-axis outside");
    }

    #[test]
    fn supports_are_outward_on_octant() {
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        for g in c.generators() {
            for s in c.supports() {
                assert!(
                    g.dot(s) <= 1e-9,
                    "generator {g:?} not on inner side of {s:?}"
                );
            }
        }
    }

    #[test]
    fn centroid_direction_is_strictly_interior() {
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        let centroid = Vector3::X + Vector3::Y + Vector3::Z;
        assert!(c.contains(&centroid));
        for s in c.supports() {
            assert!(
                centroid.dot(s) < -1e-6,
                "centroid not strictly inside {s:?}"
            );
        }
    }

    // ---- more property tests --------------------------------------------

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(256))]

        /// Membership is invariant to positive scaling of the query direction.
        #[test]
        fn prop_scale_invariance(
            (cone, _gens) in pointed_cone(),
            x in -3.0f64..3.0, y in -3.0f64..3.0, z in -3.0f64..3.0,
            k in 0.01f64..100.0,
        ) {
            let d = Vector3::new(x, y, z);
            if d.magnitude() < 1e-6 { return Ok(()); }
            prop_assert_eq!(cone.contains(&d), cone.contains(&(d * k)));
        }

        /// Every support is unit length and outward (non-positive on all generators).
        #[test]
        fn prop_supports_unit_and_outward((cone, _gens) in pointed_cone()) {
            for s in cone.supports() {
                prop_assert!((s.magnitude() - 1.0).abs() < 1e-9, "support not unit");
                for g in cone.generators() {
                    prop_assert!(g.dot(s) <= 1e-7, "generator on wrong side of support");
                }
            }
        }

        /// Every generator is unit length.
        #[test]
        fn prop_generators_unit((cone, _gens) in pointed_cone()) {
            for g in cone.generators() {
                prop_assert!((g.magnitude() - 1.0).abs() < 1e-9);
            }
        }

        /// The apex (origin) is in every cone.
        #[test]
        fn prop_apex_contained((cone, _gens) in pointed_cone()) {
            prop_assert!(cone.contains(&Vector3::ZERO));
        }

        /// Building the cone from a permutation of the input rays yields the
        /// same support set.
        #[test]
        fn prop_permutation_invariance((_cone, gens) in pointed_cone()) {
            let mut rev = gens.clone();
            rev.reverse();
            let a = PolyhedralCone::from_generators(&gens);
            let b = PolyhedralCone::from_generators(&rev);
            prop_assert_eq!(a.supports().len(), b.supports().len());
            for s in a.supports() {
                prop_assert!(b.supports().iter().any(|t| (*t - *s).magnitude() < 1e-7));
            }
        }

        /// Convexity: the sum (a conic combination) of any two generators is
        /// contained.
        #[test]
        fn prop_sum_of_two_generators_contained((cone, _gens) in pointed_cone()) {
            let gens = cone.generators();
            if gens.len() >= 2 {
                let d = gens[0] + gens[1];
                prop_assert!(cone.contains(&d), "sum of two generators not contained");
            }
        }

        /// The centroid (sum) of all generators is contained.
        #[test]
        fn prop_centroid_contained((cone, _gens) in pointed_cone()) {
            let mut d = Vector3::ZERO;
            for g in cone.generators() {
                d = d + *g;
            }
            if d.magnitude() > 1e-6 {
                prop_assert!(cone.contains(&d));
            }
        }

        /// Canonicalization is idempotent: rebuilding from the canonical
        /// generators reproduces the same cone.
        #[test]
        fn prop_canonicalization_idempotent((cone, _gens) in pointed_cone()) {
            let rebuilt = PolyhedralCone::from_generators(cone.generators());
            prop_assert_eq!(rebuilt.generators().len(), cone.generators().len());
            prop_assert_eq!(rebuilt.supports().len(), cone.supports().len());
            for g in cone.generators() {
                prop_assert!(rebuilt.generators().iter().any(|h| (*h - *g).magnitude() < 1e-7));
            }
        }

        /// The polar's supports are exactly the original generators.
        #[test]
        fn prop_polar_supports_are_generators((cone, _gens) in pointed_cone()) {
            let p = cone.polar();
            prop_assert_eq!(p.supports().len(), cone.generators().len());
            for g in cone.generators() {
                prop_assert!(p.supports().iter().any(|s| (*s - *g).magnitude() < 1e-9));
            }
        }

        /// A direction strictly inside (the generator centroid, nudged) stays
        /// contained; its antipode does not.
        #[test]
        fn prop_interior_and_antipode((cone, _gens) in pointed_cone()) {
            let mut c = Vector3::ZERO;
            for g in cone.generators() { c = c + *g; }
            if c.magnitude() < 1e-6 { return Ok(()); }
            prop_assert!(cone.contains(&c));
            prop_assert!(!cone.contains(&(-c)), "antipode of interior in pointed cone");
        }
    }

    // ---- batch 3: more configurations + structural invariants -----------

    #[test]
    fn obtuse_three_face_corner() {
        // Three faces tilted up, 120° apart in the xy plane — a wide corner.
        let c = PolyhedralCone::from_generators(&[
            nrm(1.0, 0.0, 0.3),
            nrm(-0.5, 0.866, 0.3),
            nrm(-0.5, -0.866, 0.3),
        ]);
        assert_eq!(c.supports().len(), 3);
        assert!(c.contains(&Vector3::Z));
        assert!(!c.contains(&(-Vector3::Z)));
    }

    #[test]
    fn acute_three_face_corner() {
        let c = PolyhedralCone::from_generators(&[
            nrm(0.2, 0.0, 1.0),
            nrm(-0.1, 0.17, 1.0),
            nrm(-0.1, -0.17, 1.0),
        ]);
        assert_eq!(c.supports().len(), 3);
        assert!(c.contains(&Vector3::Z));
    }

    #[test]
    fn hexagonal_fan_has_six_supports() {
        let g: Vec<Vector3> = (0..6)
            .map(|k| {
                let a = std::f64::consts::TAU * (k as f64) / 6.0;
                nrm(a.cos(), a.sin(), 1.0)
            })
            .collect();
        let c = PolyhedralCone::from_generators(&g);
        assert_eq!(c.generators().len(), 6);
        assert_eq!(c.supports().len(), 6);
    }

    #[test]
    fn octant_supports_are_distinct() {
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        let s = c.supports();
        for i in 0..s.len() {
            for j in (i + 1)..s.len() {
                assert!((s[i] - s[j]).magnitude() > 1e-6, "duplicate support");
            }
        }
    }

    #[test]
    fn polar_of_full_space_is_zero_cone() {
        let z = PolyhedralCone::full_space().polar();
        assert!(z.contains(&Vector3::ZERO));
        assert!(!z.contains(&Vector3::X), "polar of R³ is {{0}}");
    }

    #[test]
    fn different_corners_have_different_supports() {
        let a = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        let b = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, -Vector3::Z]);
        // The −Z-flipped corner must differ in at least one support.
        assert!(
            a.supports().iter().any(|s| !has_vec(b.supports(), *s)),
            "distinct corners share all supports"
        );
    }

    #[test]
    fn cone_edge_direction_is_on_boundary() {
        // X+Y is the edge of the octant between the −X and −Y faces (and on the
        // −Z face plane) — contained, on the boundary.
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        assert!(c.contains(&(Vector3::X + Vector3::Y)));
    }

    #[test]
    fn mixed_sign_corner_three_supports() {
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, -Vector3::Z]);
        assert_eq!(c.supports().len(), 3);
        assert!(
            c.contains(&Vector3::new(1.0, 1.0, -1.0)),
            "interior of mixed corner"
        );
    }

    #[test]
    fn each_octant_generator_lies_on_two_faces() {
        // Every extreme ray is the intersection of ≥2 supporting planes.
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        for g in c.generators() {
            let on = c
                .supports()
                .iter()
                .filter(|s| g.dot(s).abs() < 1e-9)
                .count();
            assert!(on >= 2, "generator {g:?} on only {on} faces");
        }
    }

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(256))]

        /// No two supports are near-duplicates.
        #[test]
        fn prop_supports_distinct((cone, _gens) in pointed_cone()) {
            let s = cone.supports();
            for i in 0..s.len() {
                for j in (i + 1)..s.len() {
                    prop_assert!((s[i] - s[j]).magnitude() > 1e-7, "duplicate support");
                }
            }
        }

        /// No two generators are near-duplicates.
        #[test]
        fn prop_generators_distinct((cone, _gens) in pointed_cone()) {
            let g = cone.generators();
            for i in 0..g.len() {
                for j in (i + 1)..g.len() {
                    prop_assert!((g[i] - g[j]).magnitude() > 1e-7, "duplicate generator");
                }
            }
        }

        /// Structural: every extreme ray (generator) is the intersection of at
        /// least two supporting planes.
        #[test]
        fn prop_generator_on_two_faces((cone, _gens) in pointed_cone()) {
            for g in cone.generators() {
                let on = cone.supports().iter().filter(|s| g.dot(s).abs() < 1e-6).count();
                prop_assert!(on >= 2, "generator on fewer than 2 faces: {on}");
            }
        }
    }
}
