//! Convex polyhedral cones in R³ — the substrate for smooth-B-Rep contact
//! determination (Crozet, Ch. 3).
//!
//! A pointed convex polyhedral cone `C ⊆ R³` at the origin has two dual
//! representations:
//!   * **V-rep** `generators`: extreme unit rays, `C = { Σ λᵢ gᵢ : λᵢ ≥ 0 }`.
//!   * **H-rep** `supports`: outward unit face normals, `C = { x : x·sⱼ ≤ 0 }`.
//!
//! The two are **polar duals**: the polar cone `C° = { y : x·y ≤ 0 ∀ x ∈ C }`
//! has `C`'s supports as its generators and vice-versa, so [`polar`] is just a
//! swap. The V↔H conversion is one routine ([`dual_extreme_rays`]): the extreme
//! rays of `{ y : vᵢ·y ≤ 0 }` are the pairwise plane intersections `vᵢ × vⱼ`
//! kept iff every other constraint holds — which converts generators→supports
//! *and* supports→generators (they're duals of each other).
//!
//! These power the CD critical-point gate (a footpoint pair is a true local
//! minimum-distance only if the separation direction lies in both features'
//! normal cones) and feature-pair culling (two cones with no common ray cannot
//! contact).
//!
//! # Scope (slice 1)
//! Correct for pointed cones whose generators span ≥ 3 dimensions (the vertex-
//! cone case) and for the full-space cone. Planar (2-generator edge) cones and
//! the cone-intersection / dilation operations are the next slices.
//!
//! # References
//! Crozet, *Efficient contact determination between B-Rep solids*, §3.2–3.4;
//! Rockafellar, *Convex Analysis*, §14 (polar cones).
#![allow(clippy::indexing_slicing)]

use crate::math::Vector3;

/// Angular epsilon for cone membership / dedup (radians-ish, on unit vectors).
const CONE_EPS: f64 = 1e-9;

/// A convex polyhedral cone in R³, stored in both dual representations.
#[derive(Debug, Clone)]
pub struct PolyhedralCone {
    /// Extreme unit rays (V-rep). Empty ⇒ the cone is `{0}` or the full space
    /// (disambiguated by `supports`).
    generators: Vec<Vector3>,
    /// Outward unit face normals (H-rep): `x ∈ C ⇔ x·sⱼ ≤ 0 ∀ j`. Empty with
    /// non-empty `generators` ⇒ the full space R³ (no constraints).
    supports: Vec<Vector3>,
}

impl PolyhedralCone {
    /// The whole space R³ (no supporting constraints). `contains` is always
    /// true. A sentinel generator records non-emptiness.
    pub fn full_space() -> Self {
        Self {
            generators: vec![
                Vector3::X,
                -Vector3::X,
                Vector3::Y,
                -Vector3::Y,
                Vector3::Z,
                -Vector3::Z,
            ],
            supports: Vec::new(),
        }
    }

    /// Build a cone from its generating rays (V-rep). Computes the dual
    /// supports (H-rep) and **canonicalizes the V-rep to its extreme rays** —
    /// redundant input rays (those interior to the conic hull of the others)
    /// are dropped, so `generators` is minimal and `generators ⇄ supports` is a
    /// clean polar round-trip. Rays are normalized and de-duplicated; zero rays
    /// are dropped.
    pub fn from_generators(rays: &[Vector3]) -> Self {
        let raw = normalize_dedup(rays);
        let supports = dual_extreme_rays(&raw);
        // The extreme rays are determined by the faces; recovering them from
        // the supports yields the minimal generator set. (When `supports` is
        // empty the cone is the full space / degenerate — keep the raw rays.)
        let generators = if supports.is_empty() {
            raw
        } else {
            dual_extreme_rays(&supports)
        };
        Self {
            generators,
            supports,
        }
    }

    /// The **normal cone** of a vertex: the cone generated by the outward
    /// normals of the faces meeting there. Its [`polar`] is the tangent cone
    /// (the directions that stay inside the solid to first order).
    pub fn normal_cone(face_outward_normals: &[Vector3]) -> Self {
        Self::from_generators(face_outward_normals)
    }

    /// Extreme unit rays (V-rep).
    pub fn generators(&self) -> &[Vector3] {
        &self.generators
    }

    /// Outward unit face normals (H-rep).
    pub fn supports(&self) -> &[Vector3] {
        &self.supports
    }

    /// True iff the cone is all of R³ (no supporting constraints).
    pub fn is_full_space(&self) -> bool {
        self.supports.is_empty() && !self.generators.is_empty()
    }

    /// Polar (dual) cone `C° = { y : x·y ≤ 0 ∀ x ∈ C }`. By the polar-duality
    /// theorem this swaps the two representations.
    pub fn polar(&self) -> Self {
        Self {
            generators: self.supports.clone(),
            supports: self.generators.clone(),
        }
    }

    /// Does direction `d` (need not be unit; the zero vector is the apex, in
    /// every cone) lie inside the cone? Tested against the H-rep.
    pub fn contains(&self, d: &Vector3) -> bool {
        if self.is_full_space() {
            return true;
        }
        let scale = d.magnitude().max(1.0);
        self.supports.iter().all(|s| d.dot(s) <= CONE_EPS * scale)
    }
}

/// Extreme rays of the dual cone `{ y : vᵢ·y ≤ 0 ∀ i }`.
///
/// Each extreme ray lies on the intersection of two bounding planes, so it is
/// `± (vᵢ × vⱼ)` for some pair, kept iff it satisfies every remaining
/// constraint. Because generators and supports are polar duals, this single
/// routine performs both V→H and H→V conversion. O(n³) — fine for the small
/// face-counts of vertex cones.
fn dual_extreme_rays(vecs: &[Vector3]) -> Vec<Vector3> {
    let n = vecs.len();
    let mut rays: Vec<Vector3> = Vec::new();
    for i in 0..n {
        for j in (i + 1)..n {
            let cross = vecs[i].cross(&vecs[j]);
            let unit = match cross.normalize() {
                Ok(v) => v,
                Err(_) => continue, // parallel generators — no shared edge
            };
            for &sign in &[1.0_f64, -1.0] {
                let r = unit * sign;
                if vecs.iter().all(|v| v.dot(&r) <= CONE_EPS) {
                    if !rays.iter().any(|e| (*e - r).magnitude() < CONE_EPS) {
                        rays.push(r);
                    }
                }
            }
        }
    }
    rays
}

/// Normalize each ray and drop near-duplicates and zeros.
fn normalize_dedup(rays: &[Vector3]) -> Vec<Vector3> {
    let mut out: Vec<Vector3> = Vec::new();
    for r in rays {
        if let Ok(u) = r.normalize() {
            if !out.iter().any(|e| (*e - u).magnitude() < CONE_EPS) {
                out.push(u);
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    // ---- known closed-form: cube vertex ---------------------------------

    #[test]
    fn cube_vertex_normal_cone_supports() {
        // Vertex of [0,L]³ at the +++ corner: incident faces' outward normals
        // are +X,+Y,+Z; the normal cone is the +++ octant, supports the −−−.
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        assert_eq!(c.supports().len(), 3);
        for expected in [-Vector3::X, -Vector3::Y, -Vector3::Z] {
            assert!(
                c.supports()
                    .iter()
                    .any(|s| (*s - expected).magnitude() < 1e-9),
                "missing support {expected:?} in {:?}",
                c.supports()
            );
        }
    }

    #[test]
    fn cube_vertex_membership() {
        let c = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]);
        assert!(c.contains(&Vector3::new(1.0, 1.0, 1.0)), "interior");
        assert!(c.contains(&Vector3::X), "boundary ray");
        assert!(!c.contains(&Vector3::new(-1.0, -1.0, -1.0)), "antipode");
        assert!(!c.contains(&(-Vector3::X)), "opposite face");
    }

    #[test]
    fn cube_vertex_tangent_cone_is_opposite_octant() {
        // Polar of the +++ normal cone is the −−− tangent cone (inward dirs).
        let tangent = PolyhedralCone::normal_cone(&[Vector3::X, Vector3::Y, Vector3::Z]).polar();
        assert!(tangent.contains(&Vector3::new(-1.0, -1.0, -1.0)), "inward");
        assert!(!tangent.contains(&Vector3::new(1.0, 1.0, 1.0)), "outward");
    }

    // ---- property tests over random pointed cones -----------------------

    /// A pointed cone: 3–5 generators all within the hemisphere around +Z
    /// (z-component ≥ 0.3), so the cone is strictly contained in z > 0 and its
    /// antipodes are guaranteed outside.
    fn pointed_cone() -> impl Strategy<Value = (PolyhedralCone, Vec<Vector3>)> {
        prop::collection::vec((-1.0f64..1.0, -1.0f64..1.0, 0.3f64..1.0), 3..6).prop_filter_map(
            "non-degenerate pointed cone",
            |raw| {
                let gens: Vec<Vector3> = raw
                    .into_iter()
                    .filter_map(|(x, y, z)| Vector3::new(x, y, z).normalize().ok())
                    .collect();
                if gens.len() < 3 {
                    return None;
                }
                let cone = PolyhedralCone::from_generators(&gens);
                // Need a genuinely bounded (pointed, supported) cone for the
                // antipode oracle to hold.
                if cone.supports().is_empty() {
                    return None;
                }
                Some((cone, gens))
            },
        )
    }

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(256))]

        /// Every generator lies in its own cone.
        #[test]
        fn generators_are_contained((cone, gens) in pointed_cone()) {
            for g in &gens {
                prop_assert!(cone.contains(g), "generator {g:?} not in cone {cone:?}");
            }
        }

        /// Any non-negative combination of generators is inside; its antipode
        /// (for a pointed cone) is outside. Labels membership without solving it.
        #[test]
        fn conic_combos_in_antipodes_out(
            (cone, gens) in pointed_cone(),
            weights in prop::collection::vec(0.0f64..1.0, 3..6),
        ) {
            let mut d = Vector3::ZERO;
            for (g, &w) in gens.iter().zip(weights.iter()) {
                d = d + *g * w;
            }
            if d.magnitude() < 1e-6 {
                return Ok(()); // all-zero weights → apex, skip
            }
            prop_assert!(cone.contains(&d), "conic combo {d:?} not in cone");
            prop_assert!(!cone.contains(&(-d)), "antipode {:?} in pointed cone", -d);
        }

        /// Polar duality round-trips: recomputing the extreme rays of the dual
        /// of the supports recovers the generators (as a set). This validates
        /// the V↔H conversion against itself.
        #[test]
        fn duality_round_trips((cone, _gens) in pointed_cone()) {
            let recovered = super::dual_extreme_rays(cone.supports());
            // recovered should equal cone.generators() as a set.
            for g in cone.generators() {
                prop_assert!(
                    recovered.iter().any(|r| (*r - *g).magnitude() < 1e-7),
                    "generator {g:?} not recovered from supports; got {recovered:?}"
                );
            }
            prop_assert_eq!(recovered.len(), cone.generators().len());
        }

        /// `polar` is an involution: `(C°)° == C`.
        #[test]
        fn polar_is_involution((cone, _gens) in pointed_cone()) {
            let back = cone.polar().polar();
            prop_assert_eq!(back.generators().len(), cone.generators().len());
            for g in cone.generators() {
                prop_assert!(back.generators().iter().any(|h| (*h - *g).magnitude() < 1e-9));
            }
        }
    }
}
